apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-app
  namespace: dev
  labels:
    app: daemonset-app
spec:
  selector:
    matchLabels:
      app: daemonset-app
  template:
    metadata:
      labels:
        app: daemonset-app
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: daemonset-app
        image: zhuzha/app
        imagePullPolicy: IfNotPresent
        resources:
         limits:
          memory: "1Gi"
          cpu: "500m"
         requests:
          memory: "500m"
          cpu: "222m"
        ports:
         - name: app-port
           containerPort: 8888
      terminationGracePeriodSeconds: 30
