apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-vol
  namespace: dev
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "$HOME/data"
