apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-vol
  namespace: dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
